#!/usr/bin/env perl

use strict;
use warnings;

use Net::SMTP;
#my $host = 'mx1.sophos.com';
#my $host = 'localhost:8124';
my $host = '8.19.41.48:8124';
my $from = 'tragicflaw@gmail.com';
my $to   = 'invite@example.com';

my $file = shift || die "Usage: $0 email_file\n";

open(my $FH, "<$file") or die "Error opening file '$file': $!";

my $s = Net::SMTP->new($host,
            Timeout => 30,
            Debug   => 1);

if (!defined($s)) {
   die "Error connecting to host '$host'\n"; 
}

$s->mail($from);
$s->to($to);
$s->data();

while(my $line = <$FH>) {
    $s->datasend($line);
}
$s->quit();
close($FH) or die "Error closing '$file': $!";

